version: "3.7"

services:
  screen-explorer-client-prod:
    container_name: screen-explorer-client-prod
    restart: always
    init: true
    build:
      context: ./
      dockerfile: docker/prod/Dockerfile
    ports:
      - "8080:80"
