version: "3.7"

services:
  screen-explorer-client-ssr:
    container_name: screen-explorer-client-ssr
    restart: always
    init: true
    build:
      context: ./
      dockerfile: docker/ssr/Dockerfile
    ports:
      - "8080:4000"
