version: "3.7"

services:
  screen-explorer-nginx:
    container_name: screen-explorer-nginx
    restart: always
    init: true
    image: nginx:1.19.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
      - /docker-volumes/etc/letsencrypt/live/screenexplorer.biz/fullchain.pem:/etc/letsencrypt/live/screenexplorer.biz/fullchain.pem
      - /docker-volumes/etc/letsencrypt/live/screenexplorer.biz/privkey.pem:/etc/letsencrypt/live/screenexplorer.biz/privkey.pem
      - /docker-volumes/data/letsencrypt:/data/letsencrypt
      - /docker-volumes/var/log/nginx:/var/log/nginx
    depends_on:
      - screen-explorer-server-api
      - screen-explorer-client
    networks:
      - screen-explorer-network

  screen-explorer-server-api:
    container_name: screen-explorer-server-api
    restart: always
    init: true
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - screen-explorer-redis
    command: npm run start:prod
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=production
    networks:
      - screen-explorer-network

  screen-explorer-redis:
    container_name: screen-explorer-redis
    restart: always
    init: true
    image: redis:6.0.3
    networks:
      - screen-explorer-network

  screen-explorer-client:
    container_name: screen-explorer-client
    restart: always
    init: true
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - screen-explorer-network

networks:
  screen-explorer-network:
    driver: overlay
